apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
  labels:
    app: member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: member
          image: 496278789073.dkr.ecr.ap-northeast-1.amazonaws.com/skccuser13-member:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/memberMgmts'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/memberMgmts'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
